# Generated by Django 4.1.7 on 2023-07-17 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.IntegerField(choices=[(1, 'Single Pass'), (2, 'Return Pass'), (3, 'Seven Day Pass')], unique=True)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Two Wheeler'), (2, 'Four Wheeler')])),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.IntegerField(choices=[(1, 'Single Pass'), (2, 'Return Pass'), (3, 'Seven Day Pass')])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.toll')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles_passed', models.PositiveIntegerField(default=0)),
                ('toll_charges_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.booth')),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.toll'),
        ),
    ]
