# Generated by Django 4.1.7 on 2023-07-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='booth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.booth'),
        ),
    ]
